// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGiHAlXhZkB_c9Qgs-i7sETh4HcT09FIU',
    appId: '1:810910395746:web:97a1d59ff8fd98dbaa903b',
    messagingSenderId: '810910395746',
    projectId: 'notes-68d1c',
    authDomain: 'notes-68d1c.firebaseapp.com',
    storageBucket: 'notes-68d1c.firebasestorage.app',
    measurementId: 'G-ZG6Z3KZFVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB74BEPvzRk25pEFAYN4M3QSMG5RuJramU',
    appId: '1:810910395746:android:972658167cf5b80caa903b',
    messagingSenderId: '810910395746',
    projectId: 'notes-68d1c',
    storageBucket: 'notes-68d1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnip_WffJ1f3m7A0jlhGg10b-jiLzmq1Q',
    appId: '1:810910395746:ios:67d5253400ef832baa903b',
    messagingSenderId: '810910395746',
    projectId: 'notes-68d1c',
    storageBucket: 'notes-68d1c.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnip_WffJ1f3m7A0jlhGg10b-jiLzmq1Q',
    appId: '1:810910395746:ios:67d5253400ef832baa903b',
    messagingSenderId: '810910395746',
    projectId: 'notes-68d1c',
    storageBucket: 'notes-68d1c.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGiHAlXhZkB_c9Qgs-i7sETh4HcT09FIU',
    appId: '1:810910395746:web:e9903b4174ecc458aa903b',
    messagingSenderId: '810910395746',
    projectId: 'notes-68d1c',
    authDomain: 'notes-68d1c.firebaseapp.com',
    storageBucket: 'notes-68d1c.firebasestorage.app',
    measurementId: 'G-GXW2SV4N2D',
  );
}
